name: Deploy Portfolio to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy to Namecheap via FTP
        env:
          LFTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "set ssl:verify-certificate no
          mirror -R ./ ./
          quit" | lftp -u "${{ secrets.FTP_USERNAME }}" --env-password "${{ secrets.FTP_SERVER }}"



