name: Deploy Portfolio to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Configure .netrc for FTP credentials
        run: |
          echo "machine ${secrets.FTP_SERVER}" > ~/.netrc
          echo "login ${secrets.FTP_USERNAME}" >> ~/.netrc
          echo "password ${secrets.FTP_PASSWORD}" >> ~/.netrc

      - name: Deploy to Namecheap via FTP
        run: |
          lftp -e "set ssl:verify-certificate no; mirror -R ./ ./; quit"








