name: Deploy Portfolio to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Deploy to Namecheap via FTP
        run: |
          echo "set ssl:verify-certificate no" > lftp_script.txt
          echo "mirror -R ./ ./" >> lftp_script.txt
          echo "quit" >> lftp_script.txt
          lftp -u "${{ secrets.FTP_USERNAME }}" -e "source lftp_script.txt" "${{ secrets.FTP_SERVER }}"





